[general]
import = ["~/.config/alacritty/melange_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[window]
opacity = 0.9
option_as_alt = "OnlyLeft"

[window.padding]
x = 3
y = 3
